import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  trends: React.ReactNode;
  users: React.ReactNode;
}

export default function RootLayout(props: Readonly<RootLayoutProps>) {
  const { children, trends, users } = props;

  return (
    <html lang="en" >
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        {trends}
        {users}
      </body>
    </html>
  );
}
